apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: mongoapi
data:
  MongoDb__ConnectionString: >-
    mongodb://mongo-0.mongo-headless:27017,mongo-1.mongo-headless:27017,mongo-2.mongo-headless:27017,mongo-3.mongo-headless:27017,mongo-4.mongo-headless:27017/?replicaSet=rs0
  MongoDb__DatabaseName: "NotificationsDb"
  RabbitMq__Host: "rabbitmq"
